name = "MimiRegistry"
uuid = "fbe175fe-15e2-11e9-3f9b-155eeddbb53e"
repo = "https://github.com/anthofflab/MimiRegistry.git"

description = """
Registry for Mimi models
"""

[packages]
54b9761e-41d9-11e9-3151-3dc5fec6a45b = { name = "MimiRICE2010", path = "MimiRICE2010" }
