name = "MimiRegistry"
uuid = "fbe175fe-15e2-11e9-3f9b-155eeddbb53e"
repo = "https://github.com/anthofflab/MimiRegistry.git"

description = """
Registry for Mimi models
"""

[packages]
be3a4780-1b43-11e9-0c60-054b7c4010b8 = { name = "MimiTestModel", path = "MimiTestModel"}
f500bf80-3be4-11e9-17ce-876a9a04c77e = { name = "MimiDice2013", path = "MimiDice2013"}
_ = { name = "mimi-dice-2013", path = "mimi-dice-2013"}